### ISSUE TITLE
Updating the existing pyduofern installation in HA

### ISSUE THREAD

**Issue by mmatesic01** [gluap/pyduofern#12]
Hello,
How can I update an existing (working) pyduofern integration on my HA? 
Do I loose anything with upgrade?

Thank you for the help.

**Comment by gluap** [comment]
@mmatesic01  you can upgrade by replacing your old version with the current ``custom_components/duofern``. It has a requirement to the matching pyduofern module version so homeassistant will install the correct version on startup.

If you want extra safety, you can take backups of your former ``duofern.json`` file. 
In case you have a very old version running you may have to adapt the lines in the config file to current format. (look at the custom component readme for the current format). If you want to make extra triple sure you can also backup the ``custom_components`` directory.

You should (**caveat**: I never tried downgrading) be able to downgrade by simply going back to your old custom_components directory. If that does not suffice you may have to manually remove the ``pyduofern`` module (``pip uninstall pyduofern`` if you are running homeassistant from a venv). I'm not sure if homeassistant will downgrade it upon finding a reduced required version.
