### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by Boby71** [gluap/pyduofern#29]
I don't know what happened, but when I try to to start the script, I get the following error:
```openhabian@openHABianPi:/ $ sudo python3 /home/openhabian/.local/bin/duofern_cli.py
Traceback (most recent call last):
  File "/home/openhabian/.local/bin/duofern_cli.py", line 26, in <module>
    from pyduofern.duofern_stick import DuofernStickThreaded
ModuleNotFoundError: No module named 'pyduofern'
```
I'm an absolute noob in python, but when I try to install the package it looks fine:
```
openhabian@openHABianPi:/ $ pip3 install pyduofern
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Requirement already satisfied: pyduofern in /home/openhabian/.local/lib/python3.7/site-packages (0.34.1)
Requirement already satisfied: pyserial-asyncio in /home/openhabian/.local/lib/python3.7/site-packages (from pyduofern) (0.5)
Requirement already satisfied: pyserial in /home/openhabian/.local/lib/python3.7/site-packages (from pyduofern) (3.5)
openhabian@openHABianPi:/ $

```
Where's my mistake/problem? Thanks!

**Comment by Boby71** [comment]
I used sudo to call python; after removing sudo everything was fine again

**Comment by Boby71** [comment]
Also, take care that installing pyduofern using SUDO (sudo pip3 install pyduofern) - otherwise you could run into the same problem  as well (Modulenotfounderror). It may depend your installation, but if you run into this error it's an easy task to check.

**Comment by gluap** [comment]
Let me add that whether sudo is required or not depends on the setup. A lot of people use virtualenvs / venvs to run python modules like this one. If a virtualenv/venv is used, always ``pip`` from the venv should be used. 

Some people actually install third party modules in their OS, in this case ``sudo pip``is the way to go (I'd always recommend working with venvs though, as does, for instance, the homeassistant core documentation). 

Finally there's a third way in case only one user wants to use pyduofern from their standard interpreter but still not pollute the system python libraries: in this case using ``pi``p from the OS but with an extra ``--user`` as ``pip install --user`` will install the modules in the overlay directory for the currently active user. ``.local/bin`` etc...
