### ISSUE TITLE
Question - no issue

### ISSUE THREAD

**Issue by FaserF** [gluap/pyduofern#30]
Hi, first thank you for your efforts! Currently I havent bought products from rademacher, but I want to.
I just want to be sure that I have understood the project correctly before buying something that expensive.

When I am going to buy rolltron products (for example the rademacher rolltron 1200), then I will only need the duofern usb stick plugged into my raspberry pi running Homeassistant OS and with this custom integration it should work? 
I just want to be sure, that Homeassistant OS will work fine and that I dont need another bridge from rademacher.

Are the „ DuoFern Heizkörperstellantrieb 2 “ also supported?

Thank you in advance for answering the questions :)

**Comment by gluap** [comment]
pyduofern does not require any additional hardware beyond the usb stick. If you know your way around Homeassistant OS and can manage installing custom integrations in it you should be able to get it running. Personally I'm running "Homeassistant core" but I've heard of people using pyduofern with Homeassistant OS (tried it myself once back when it was still called hassio). There is also a HACS custom repository for pyduofern (https://github.com/gluap/pyduofern-hacs) that should make installing in Homeassistant OS easier if you already use HACS.

The "Heizkörperstellantrieb" is not supported - depending on your python skills and time to spare you may be able to add the support yourself. As far as I can tell the FHEM module this is based on already supports the Heizkörperstellantrieb so there should be no t

**Comment by FaserF** [comment]
Thank you
