### ISSUE TITLE
RolloTube

### ISSUE THREAD

**Issue by FrankR59** [gluap/pyduofern#37]
Hi, I just came across your pyduofern. I own an old homepilot 1 and I would like to get rid of it and use it's DuoFern stick standalone. I have paired 13 Rollotube RTFM 10/16 Z Funk motors. All of them had a label with a 6-digit code for pairing and I also know the device codes that I use together with my homepilot's http-api. As I am afraid of a hardware breakdown I am looking for a solution to only use the duofern stick. I once saw the perl code from fhem but I don't use fhem (only openhab) and also I am not at all familiar with perl. I can read and write c, c++ and python.
Is it possible to use your python module on a raspberry pi or similar and communicate with the stick attached to the pi? I guess it would not be necessary to pair the motors again. Am I right? What functions do I have to use in order to send commands to my motors?
Best regards
Frank

**Comment by gluap** [comment]
Hi,

Yes the module runs euth the stick on a raspberry pi.

Most people use it in homeassistant though, as writing ones own program for home automation is a rather tedious task and home automation software such as fhem or homeassistant already has all the ui one could wish for - for instance to open/close based on time of day, sun inclination or even a weather forecast. Pyduofern is available as a custom add-on for home assistant hacs [here](https://github.com/gluap/pyduofern-hacs) 

I can't tell whether coming from homepilot you need to re-pair - i only ever used my shutters with pyduofern.

Regarding how to use please adhere to the Readme and should that be insufficient have a look at the cli that comes included and allows to send duofern commands.

Cheers
Paul

**Comment by FrankR59** [comment]
Many Thanks. I'll give it a try
Best regards
Frank
