### ISSUE TITLE
pyduofern not available after reboot

### ISSUE THREAD

**Issue by SkinnyNorris123** [gluap/pyduofern#39]
Good morning,
thank you for implementing this device in HA. It has worked like a charm.
But, after an reboot of the Rpi the needed directory's are not longer available and the devices in HA are gone.
.
I installed everything as mentioned here (pip3 install pyduofern)
and then configured it via the CLI (duofern_cli.py).
Following a reboot HA can no longer talk to the blinds and looking into the directory /usr/lib/python3.12/site-packages/
pyduofern is gone:

```
# pwd                        
/usr/lib/python3.12/site-packages
# ls -l pyduo*      
zsh: no matches found: pyduo*
```
I m more or less sure I m doing something pretty easy wrong, can you maybe point me to the point ?

regards
Ole

**Comment by gluap** [comment]
I'd suggest using the custom component and hacs to deploy duofern on homeassistant.

As stated in the readme:
> There is a custom component for homeassistant that can be easily deployed via hacs at https://github.com/gluap/pyduofern-hacs

No pip should be necessary for that.

Cheers
Paul 

On December 27, 2024 1:28:51 PM GMT+01:00, SkinnyNorris123 ***@***.***> wrote:
>Good morning,
>thank you for implementing this device in HA. It has worked like a charm.
>But, after an reboot of the Rpi the needed directory's are not longer available and the devices in HA are gone.
>.
>I installed everything as mentioned here (pip3 install pyduofern)
>and then configured it via the CLI (duofern_cli.py).
>Following a reboot HA can no longer talk to the blinds and looking into the directory /usr/lib/python3.12/site-packages/
>pyduofern is gone:
>
>```
># pwd                        
>/usr/lib/python3.12/site-packages
># ls -l pyduo*      
>zsh: no matches found: pyduo*
>```
>I`m more or less sure I`m doing something pretty easy wrong, can you maybe point me to the point ?
>
>regards
>Ole
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/gluap/pyduofern/issues/39
>You are receiving this because you are subscribed to this thread.
>
>Message ID: ***@***.***>
--
Paul Görgen
https://pgoergen.de

**Comment by SkinnyNorris123** [comment]
Thank you for your quick answer. Can you maybe help with a quick how to ?
![image](https://github.com/user-attachments/assets/dfe9722f-46a7-4395-915a-7df4ffb97d40)
Not sure if I understand this

**Comment by gluap** [comment]
@SkinnyNorris123 Just use hacs and follow the pyduofern 
-hacs manual for setting up with hacs. [here](https://github.com/gluap/pyduofern-hacs)

Hacs is also linked in case you don't have it set up yet.

**Comment by SkinnyNorris123** [comment]
Thanks a lot, I was really to stupid to do this. At the end this was very straight forward.
