### ISSUE TITLE
DuoFern 70000093 not available anymore

### ISSUE THREAD

**Issue by thwe1966** [gluap/pyduofern#7]
Hi,

the USB-Stick DuoFern 70000093 is not available anymore.
The DuoFern 70000093 is a Z-Wave USB stick,  can it be replaced by a Aeotec AEOEZW090-C?

**Comment by gluap** [comment]
Hi,
Rademacher homepilot can run both zwave and the proprietary duofern protocol but the two are not the same (even though rademacher sells devices for both). Duofern is an older proprietary protocol by rademacher, as far as I know it predates zwave. The 70000093 is **not** a zwave stick. pyduofern is only usable for duofern and as far as I know the 70000093 is the only stick that supports it. 

**edit**: After research it seems 70000093 is still available in some online shops at the time of writing this: https://www.enobi.de/steuerungen/rademacher-funksystem-duofern/rm0195

**Comment by thwe1966** [comment]
Thank you for your answer and also the reference to the page on which the stick is still orderable - I had overlooked.

Now order the stick and for the first time a "RolloTron Basis DuoFern 1200 Unterputz" - hope to get everything running :-)

Still a nice rest weekend

**Comment by gluap** [comment]
@thwe1966 damn you are quick. I just revisited the page and would like to emphasize that im nkt sure its the stickt. Its mentioning a second article number. And the 70000093 is mentioned as "vgl" instead so it may be a follow up product.

**Comment by thwe1966** [comment]
Thanks for the hint, everything is at my risk ;-)

**Comment by gluap** [comment]
If you test it it would be great if you could leave a note whether it works or not. So far nobody has tested it as far as I can tell (also not on FHEM whereppyduofern was ported from).

**Comment by t-animal** [comment]
@thwe1966 have you tested the stick? Does it work?

**Comment by Hypfer** [comment]
@t-animal I've ordered the stick in the shop linked by @gluap and can confirm that it is in fact the `70000093` which reports itself as `0403:6001 Future Technology Devices International, Ltd FT232 Serial (UART) IC`

Furthermore, the box states `V1901013 (04.15)`

**Comment by bcutter** [comment]
So the 9495 is some kind of successor of the 70000093?
When getting the Home Pilot 2 bridge a stick is included, seems to be this 9495.
And it is working the same way the 70000093 does (@Hypfer)?

Update: According to https://wiki.fhem.de/wiki/Rademacher_DuoFern (guys who originally ported DuoFern for FHEM) the "70000093" is the model number where "9495-UW" is the model type. So same device...
